baseURL = "https://stupefied-northcutt-0b0f82.netlify.com/"
languageCode = "en-us"
title = "b3a-dev"
theme = "timer-hugo"


# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "Talks"
        url     = "talks"
        weight  = 3
    [[menu.nav]]
        name    = "Blog"
        url     = "blog"
        weight  = 4
    [[menu.nav]]
        name    = "Contact"
        url     = "contact"
        weight  = 5

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Airspace Hugo theme"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "216514407"


    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "HI, MY NAME IS BEATRIZ & I AM A"
        description = "INSATIABLE LEARNER, PASSIONATE ABOUT TECHNOLOGY AND INNOVATION, I LOVE TO GET INVOLVED WITH OPEN SOURCE COMMUNITIES. THIS SITE SHOWCASES SOME OF MY CONTRIBUTIONS."
        btn     = true
        btnText = "Download More"
        btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "SPEAKER"
        [[params.banner.flipText]]
            title   = "DEVELOPER"
        [[params.banner.flipText]]
            title   = " WOMEN IN TECH"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        content = "Dedicated to architecture and innovation focused on cloud environments, I am an advocate for women in technology. <br> <br> Insatiable learner, I love to get involved with open source communities and contribute mainly as Speaker at technical community events. I am aiming to bring any of my ideas to life with code."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT DO YOU THINK ?"
        content = "Any project in mind that you would like to share?, would you like to propose a part2 for some of the posts?, do you have questions related to any of the contents?, please let me know. And thank you in advance for any suggestions or advice."
        btnText = "Contact with me"
        btnURL  = "/contact"
    

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = true
        title   = "Latest Contributions"
        subtitle= "I would like to share some of my latest posts, talks at technical events, interviews and my most recent projects."

    [params.footer]
        [[params.footer.socialIcon]]
            icon = "ion-social-twitter"
            url = "https://twitter.com/beatrizmrg?"

        [[params.footer.socialIcon]]
            icon = "ion-social-github"
            url = "https://github.com/b3a-dev"

        [[params.footer.socialIcon]]
            icon = "ion-ios-paper"
            url = "https://medium.com/@beatrizmrg"

